AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - test/dummy/db/schema.rb

Layout/IndentationConsistency:
  EnforcedStyle: rails

Metrics/LineLength:
  Max: 120

Style/BlockDelimiters:
  EnforcedStyle: semantic
  FunctionalMethods:
    - git_source
