version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6
      - image: elasticsearch:5.6-alpine
    steps:
      - checkout

      - restore_cache:
          name: Restore Bundler Cache
          keys:
            - bundler--{{ checksum "Gemfile" }}--{{ checksum "elasticsearch-model-transactional_callbacks.gemspec" }}
            - bundler--{{ checksum "Gemfile" }}
            - bundler

      - run: bundle check || bundle install

      - save_cache:
          key: bundler--{{ checksum "Gemfile" }}--{{ checksum "elasticsearch-model-transactional_callbacks.gemspec" }}
          paths:
            - /usr/local/bundle

      - run:
          name: Setup Test Database
          command: |
            cd test/dummy
            bundle exec rake db:test:prepare

      - run: bundle exec rake test

      - store_test_results:
          path: test/reports
